server:
  port: 8080

spring:
  application:
    name: backend-spring
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:blogdb}
    username: ${DB_USERNAME:blog_user}
    password: ${DB_PASSWORD:blog_pass}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
