/*
 * This source file was generated by the Gradle 'init' task
 */

package backend;

import backend.Java_practice.Student;
// 가져옵니다


// java 의 starting point
// main method 를 포함하는 class
// main method 도 하나의 thread 이다. main method 가 끝나면 thread 도 종료된다.

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Student student = new Student("John Doe", 20, "Computer Science");
        student.displayInfo();

    }
}



//has a 설계 